### ISSUE TITLE
Unable to Create Network Router Error 

### ISSUE THREAD

**Issue by DavidResende0** [ManageIQ/manageiq-providers-openstack#703] opened 2021-04-14 13:58 UTC
When trying to create a new Network Router using the `OpenStack Network Manager` this error occurs:

![image](https://user-images.githubusercontent.com/64800041/114719029-9cbd1700-9d04-11eb-8246-080d3db58ef1.png)

This is the backtrace from `evm.log`:
```
[----] E, [2021-04-13T16:03:13.078023 #75714:becd0] ERROR -- : MIQ(network_router_controller-wait_for_task): »Unable to create Network Router "David Resende": No credentials defined«
[----] I, [2021-04-13T16:03:13.784717 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => NetworkRouter]...
[----] I, [2021-04-13T16:03:13.787776 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => ManageIQ::Providers::NetworkManager]...
[----] I, [2021-04-13T16:03:13.901513 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => CloudTenant]...
[----] I, [2021-04-13T16:03:13.922498 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => CloudNetwork]...
[----] I, [2021-04-13T16:03:13.932461 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => VmOrTemplate]...
[----] I, [2021-04-13T16:03:14.113127 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => FloatingIp]...
[----] I, [2021-04-13T16:03:14.114023 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => CloudNetwork]...
[----] I, [2021-04-13T16:03:14.117019 #75714:becd0]  INFO -- : MIQ(MiqExpression.build_relats) Building relationship tree for: [ => SecurityGroup]...
[----] W, [2021-04-13T16:37:08.637367 #75714:be6f4]  WARN -- : MIQ(MiqExpression#convert_size_in_units_to_integer) No subtype defined for column CloudNetwork-ems_id in 'miq_report_formats.yml'
[----] W, [2021-04-13T16:37:08.638474 #75714:be6f4]  WARN -- : MIQ(MiqExpression#convert_size_in_units_to_integer) No subtype defined for column CloudNetwork-ems_id in 'miq_report_formats.yml'
[----] W, [2021-04-13T16:37:08.639074 #75714:be6f4]  WARN -- : MIQ(MiqExpression#convert_size_in_units_to_integer) No subtype defined for column CloudNetwork-ems_id in 'miq_report_formats.yml'
[----] I, [2021-04-13T16:37:18.844406 #75714:be708]  INFO -- : MIQ(MiqQueue.put) Message id: [133307436],  id: [], Zone: [OpenStack Zone], Role: [ems_operations], Server: [], MiqTask id: [436018], Ident: [generic], Target id: [], Instance id: [8], Task id: [], Command: [ManageIQ::Providers::Openstack::NetworkManager.create_network_router], Timeout: [600], Priority: [20], State: [ready], Deliver On: [], Data: [], Args: [{:name=>"David Resende", :admin_state_up=>"true", :ems_id=>"8", :cloud_subnet_id=>"", :cloud_tenant=>#<ManageIQ::Providers::Openstack::CloudManager::CloudTenant id: 5, name: "cloud-southeast", description: "", enabled: true, ems_ref: "7288d564106f4046b3898f3c642cf387", ems_id: 7, created_at: "2017-10-06 16:56:43", updated_at: "2017-10-06 16:56:43", type: "ManageIQ::Providers::Openstack::CloudManager::Clou...", parent_id: nil>, :task_id=>436018}]
[----] I, [2021-04-13T16:37:18.844460 #75714:be708]  INFO -- : MIQ(MiqTask.generic_action_with_callback) Task: [436018] Queued the action: [creating Network Router for user admin] being run for user: [admin]
[----] I, [2021-04-13T16:37:18.999277 #75111:ae24]  INFO -- : MIQ(MiqQueue#deliver) Message id: [133307436], Delivering...
[----] I, [2021-04-13T16:37:19.002113 #75111:ae24]  INFO -- : MIQ(MiqTask#update_status) Task: [436018] [Active] [Ok] [Task starting]
[----] I, [2021-04-13T16:37:19.006600 #75111:ae24]  INFO -- : MIQ(ManageIQ::Providers::Openstack::CloudManager#with_provider_connection) Connecting through ManageIQ::Providers::Openstack::CloudManager: [OpenStack]
[----] E, [2021-04-13T16:37:19.010157 #75111:ae24] ERROR -- : MIQ(ManageIQ::Providers::Openstack::NetworkManager::NetworkRouter.raw_create_network_router) router=[], error: No credentials defined
[----] E, [2021-04-13T16:37:19.010296 #75111:ae24] ERROR -- : MIQ(MiqQueue#deliver) Message id: [133307436], Error: [No credentials defined]
[----] I, [2021-04-13T16:37:19.010354 #75111:ae24]  INFO -- : MIQ(MiqQueue#delivered) Message id: [133307436], State: [error], Delivered in [0.011088] seconds
[----] I, [2021-04-13T16:37:19.011176 #75111:ae24]  INFO -- : MIQ(MiqQueue#m_callback) Message id: [133307436], Invoking Callback with args: ["Finished", "error", "No credentials defined", "nil"]
[----] I, [2021-04-13T16:37:19.011263 #75111:ae24]  INFO -- : MIQ(MiqTask#update_status) Task: [436018] [Finished] [Error] [No credentials defined]
[----] E, [2021-04-13T16:37:23.984476 #75714:210d4] ERROR -- : MIQ(network_router_controller-wait_for_task): »Unable to create Network Router "David Resende": No credentials defined«
```

**Comment by agrare** [comment] 2021-04-19 14:35
@DavidResende0 I wasn't able to reproduce this on master, I was able to create a network successfully.

If you can reproduce this can you share the environment with me?

**Comment by Fryguy** [comment] 2021-04-19 14:42
Try turning on ui.mark_translated_strings.  A lot of issues that @DavidResende0 is found that way, many times because keys of Hashes are being translated (and then later lookups into those hashes fail)

**Comment by DavidResende0** [comment] 2021-04-19 14:55
> Try turning on ui.mark_translated_strings. A lot of issues that @DavidResende0 is found that way, many times because keys of Hashes are being translated (and then later lookups into those hashes fail)

I tried running it with `mark_translated_strings` off and I'm still getting the error in master, locally.

**Comment by agrare** [comment] 2021-04-19 14:56
@DavidResende0 maybe a silly question, but do you have valid credentials for this provider?  I'm assuming it is failing to delegate from the network manager to the cloud manager for `with_provider_connection` but it is also possible that your cloud_manager doesn't have credentials set.  e.g. was this an imported database?

**Comment by DavidResende0** [comment] 2021-04-19 14:57
> @DavidResende0 maybe a silly question, but do you have valid credentials for this provider? I'm assuming it is failing to delegate from the network manager to the cloud manager for `with_provider_connection` but it is also possible that your cloud_manager doesn't have credentials set. e.g. was this an imported database?

yes it was imported

**Comment by agrare** [comment] 2021-04-19 15:24
Does this openstack provider have valid credentials?  Are you able to run a refresh for example

**Comment by agrare** [comment] 2021-04-19 15:25
If your provider doesn't have valid credentials then I think this is working as expected.  Possibly we should be checking if the provider has valid authentication in the `supports :create` block, but that is something that isn't unique to creating network routers.

**Comment by DavidResende0** [comment] 2021-04-19 16:23
So this is probably the issue then?
![image](https://user-images.githubusercontent.com/64800041/115270088-fc069700-a109-11eb-9465-12197bf5bf1f.png)

**Comment by agrare** [comment] 2021-04-19 16:25
Yes exactly, if you import a database all of the records on the providers are essentially read-only and can't have any actions done on them unless you have access to the original provider

**Comment by DavidResende0** [comment] 2021-04-19 16:28
So I would need a new provider in order to test making a new Network Router

**Comment by agrare** [comment] 2021-04-19 16:39
Not necessarily a new provider (if you know what system that is you could edit your current one and input correct credentials), but in order to do any operations on any provider you have to have valid authentication.

I'm going to close this since "Missing credentials" appears to be the valid error in this case given your Default Credentials status in that screenshot.

**Closed by agrare** 2021-04-19 16:39 UTC
Labels: bug
