### ISSUE TITLE
Issue in provisioning instance with zero root disk flavor in OpenStack

### ISSUE THREAD

**Issue by Dhamo1107** [ManageIQ/manageiq-providers-openstack#892] opened 2024-10-09 14:08 UTC
### **OpenStack Behavior:**
In OpenStack, while launching an instance with a zero root disk flavor, the following options are available under the "Source" tab:

- Select Boot Source:

    - Options: Image, Instance Snapshot, Volume, Volume Snapshot

- Create New Volume: Yes/No

    - If "Yes" is selected, additional fields appear:

        - Volume Size (GB): (Field to input volume size in GB)

        - Delete Volume on Instance Delete: Yes/No

For example, if "Create New Volume" is selected as "Yes" and a volume size of 1GB is specified, this volume is treated as the root disk.
![image](https://github.com/user-attachments/assets/7866fca2-4bde-47fa-a47c-fb43813b25b7)
![image](https://github.com/user-attachments/assets/59c53274-32c8-4ac5-b6a6-548933a21c36)

### **Issue in ManageIQ:**
In ManageIQ, there seems to be no option to specify a root disk size while provisioning an instance with a zero root disk flavor. If we try to add a volume using the "Add Volume" option in the instance provisioning page, the volume is attached as an additional volume instead of being treated as the root disk.
![image](https://github.com/user-attachments/assets/41098d09-a4f5-4d47-b760-255a4ab6f72e)
![image](https://github.com/user-attachments/assets/098458fb-0c2e-44ae-a833-069173db333e)

**Request:**
Could you guide us on how to add root disk space while provisioning an instance with a zero root disk flavor type in ManageIQ? If this feature does not exist, would it be possible to implement a way to handle root disk size in this scenario?

**Steps to Reproduce:**
Provision an instance with a zero root disk flavor in OpenStack via ManageIQ.
Attempt to add a root disk volume during provisioning.

**Expected Behavior:**
The ability to specify and add root disk size during instance provisioning with zero root disk flavor in ManageIQ, similar to the OpenStack behavior.

**Actual Behavior:**
The "Add Volume" option adds an additional volume but does not handle root disk size.

**ManageIQ version: Petrosian**

**Comment by Dhamo1107** [comment] 2024-10-10 13:44
Hi @agrare,

I would like to know if there are any updates on this issue. Please let me know if further information is needed from my side.

Thank you!

**Comment by Dhamo1107** [comment] 2024-10-15 14:21
Hi @agrare,

By using OpenStack's "Create New Volume" option, the volume is added under `/vda`.

However, when trying to add a volume using ManageIQ while provisioning an instance, the volume is added under `/vdb`.

We need to ensure that the volume is added under `/vda` while provisioning instance from ManageIQ as well. Please guide us on how to do that. Refer to the attached images where the volume is added using both OpenStack and ManageIQ.

1) Openstack (10GB is added under `/vda`):
![image](https://github.com/user-attachments/assets/9873628d-c60f-41cf-883f-ccd4a49ecdbb)

2) ManageIQ (10GB is added under `/vdb`):
![image](https://github.com/user-attachments/assets/521bc7ad-e818-4a56-b55e-7b57b97c3fb2)

Hi @Fryguy and @GilbertCherrie, Do you have any insights on this?

**Comment by agrare** [comment] 2024-10-15 15:04
Hey @Dhamo1107 sorry no I haven't gotten a chance to look at this yet.
So when we create a new volume that is done here https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb

I'm not as well versed with the openstack API as you likely are, if you can post what properties would have to be provided to make a disk a "root" volume we can update our volume_attachment code to check for that attribute and set it appropriately.

**Comment by Dhamo1107** [comment] 2024-10-16 11:26
Hi @agrare,

Thank you for your insights.

This is the OpenStack documentation on how to [Create volume from image and boot instance](https://docs.openstack.org/ocata/user-guide/cli-nova-launch-instance-from-volume.html#create-volume-from-image-and-boot-instance). From the document, I believe the parameters likely to be sent from ManageIQ to OpenStack to create that volume in vda are `--block-device` and `boot_index: 0`. I added `new_volume_attrs[:boot_index]       = 0` this in `volume_attachment.rb` file. However, I received the error message: `Block Device Mapping is Invalid: Boot sequence for the instance and image/block device mapping combination is not valid`.

![image](https://github.com/user-attachments/assets/88e29895-3a9a-4ab7-baa5-ae7ba20b42d2)

![image](https://github.com/user-attachments/assets/16ca26b4-a601-4d20-be53-e39b6f7a6b10)

**Comment by agrare** [comment] 2024-10-16 16:01
@Dhamo1107 I think the issue is that we have a "default" first volume.

https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb#L3 that is the "first" disk and you can see the default volume has `:boot_index => 0` https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb#L39-L49 so I think the issue that you're hitting is you have two volumes with `boot_index=0`

What I think we need is to check if the `source` has a root_disk (maybe root_disk_size == 0 ?  Can you check that?) and if it doesn't then we shouldn't have a default_volume.

```
volumes_attrs_list = []
volumes_attrs_list << default_volume_attributes if instance_type.root_disk_size > 0
```

Then in your `requested_volumes` the first volume that you want to create as a boot disk you would set `:boot_index => 0`

**Comment by Dhamo1107** [comment] 2024-10-17 14:26
Hi @agrare, we are encountering an issue where the volume is created under `vda`, but there is no bootable device. The issue seems to be because the volume is created without an OS image, which is likely causing the error. In the attached image of the volume_attachment.rb file:

![image](https://github.com/user-attachments/assets/5d544bd2-08a2-4ac6-b0d1-ca5c1de3f0b0)

in the `requested_volumes` block, I initially set the `uuid` as `new_volume_id`, the `source_type` as `volume`, and the `destination_type` as `volume`. However, I think the correct `source_type` should be the `image`, along with its `UUID` as `source.ems_ref`, and the `destination_type` should be `volume`. I’ve now made that change.

![image](https://github.com/user-attachments/assets/9d5428a6-0d2b-4b30-8108-12cadae65b30)

However, I’m now getting this error: `Images with destination_type volume need to have a non-zero size specified.`

![image](https://github.com/user-attachments/assets/1bce8c56-9b5c-4361-9fcd-ad6cc61d532e)

Do you have any suggestions on how to resolve this? Thanks.

**Comment by agrare** [comment] 2024-10-17 14:34
> However, I’m now getting this error: Images with destination_type volume need to have a non-zero size specified.

This error is coming from Openstack, I wonder if you need to set the size in `volume_attrs` before the `service.volumes.create(volume_attrs)` call?  Can you tell if the `service.volumes.create()` call is successful and it fails later on?

**Comment by Dhamo1107** [comment] 2024-10-17 15:55
Hi @agrare,

This is the code now i have after adding debug statements:
![image](https://github.com/user-attachments/assets/d8024f9a-bb57-4e22-8161-7a9c63bfb239)

This is the log generated for that:
![image](https://github.com/user-attachments/assets/e66ef727-afee-4c53-845b-dcddc9f0e8b7)

The volume is created in opnstack, but not attached to instance:
![image](https://github.com/user-attachments/assets/a2c49c63-632e-4eb4-9957-7cf6ab6371d1)

**Comment by agrare** [comment] 2024-10-17 17:19
So I definitely see a disk with `:name=>"root"` and `:size=>0` in that "Checking volume with attributes" log line.  Can you track down where that is coming from?

**Comment by Dhamo1107** [comment] 2024-10-17 17:26
Yes @agrare that is coming from `default_volume_attributes`

**Comment by agrare** [comment] 2024-10-17 18:44
Okay I thought if the flavor didn't have a root disk you were skipping the `default_volume_attributes`, can you tell how it is getting in there?

**Comment by Dhamo1107** [comment] 2024-10-19 08:03
Hi @agrare,

We have fixed the issue and created a PR for it. Please take a look at it:

[PR#894](https://github.com/ManageIQ/manageiq-providers-openstack/pull/894)

Thank you for your valuable insights.

**Comment by agrare** [comment] 2024-10-24 14:11
That's great @Dhamo1107 !  I do wonder how the `default_volume_attributes` values got in there if you skipped them via `volumes_attrs_list = instance_type.root_disk_size > 0 ? [default_volume_attributes] : []`.  That's my only hesitation on merging what you have there as-is

**Comment by Dhamo1107** [comment] 2024-10-24 14:46
Hi @agrare, the log indicates that the `default_volume_attributes` values showing `name: root` and `size: 0` are associated with task ID 118, which I ran before changing the condition `volumes_attrs_list = instance_type.root_disk_size > 0 ? [default_volume_attributes] : []`. After modifying the condition, task ID 119 indicates `skipping default volume attributes`, which seems to be the misunderstanding. Task ID 119 correctly shows `name: vol-test`

Thank You

**Comment by agrare** [comment] 2024-12-10 16:06
Fixed by https://github.com/ManageIQ/manageiq-providers-openstack/pull/894

**Closed by agrare** 2024-12-10 16:06 UTC
Labels: bug
